name: Sync to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      AZURE_PAT: ${{ secrets.AZURE_PAT }}

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Add Azure DevOps remote
      run: |
        git remote add azure https://$AZURE_PAT@dev.azure.com/SimplifyHealthcare/SimplifyX/_git/TestAZGitSycRepo
        git fetch azure

    - name: Push to Azure DevOps develop branch
      run: |
        git push azure HEAD:develop --force
